FROM openjdk:21-alpine

EXPOSE 8081

WORKDIR /app

ENV SPRING_SERVER_PORT=8080
ENV SPRING_DATA_SOURCE_URL=jdbc:postgresql://localhost:5433/api_products_db
ENV SPRING_DATA_SOURCE_USERNAME=admin
ENV SPRING_DATA_SOURCE_PASSWORD=admin
ENV PRING_JWT_SECRET="batman batman batman"

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline

COPY src ./src

CMD [ "./mvnw", "spring-boot:run"]